name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Убедись, что версия совпадает с твоим проектом

      - name: Restore dependencies
        run: dotnet restore working-directory: FurnitureMeasurePro

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Publish project
        run: dotnet publish FurnitureMeasurePro/ -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FurnitureMeasurePro-Build
          path: ./publish
